### ISSUE TITLE
Just Liveview / Timelaps

### ISSUE THREAD

**Issue by ETE-Design** [jameszah/ESP32-CAM-Video-Recorder#1]
Is it possible to just show liveview, and then "check / uncheck" timelapse? Would be great, and do you think you can add that feature to ESP3D? https://github.com/luc-github/ESP3D/

**Comment by jameszah** [comment]
I've thought about adding a continuous live-view, rather than the one snapshot, but it would interfere with an existing video recording.  Maybe live-view option if recording shut off.

But I don't think I can add this this to that 3D printing system - maybe the 3D printing guys could add it?
