### ISSUE TITLE
Move samples to seperate storage

### ISSUE THREAD

**Issue by petervanderwalt** [jameszah/ESP32-CAM-Video-Recorder#11]
I cannot even clone the repo on my slow internet connection, its crazy big!  Pointless to have samples as part of the code repo. Put it somewhere else (google drive, dropbox, github storage, etc) and link to it instead

**Comment by jameszah** [comment]
No problem - it went from 180 MB to 5 MB - mostly photos on the readme.

**Comment by petervanderwalt** [comment]
Thats OK (: documentation is important. Thanks will play with it tomorrow
then
