### ISSUE TITLE
Not and issue ... but great job and suggetions

### ISSUE THREAD

**Issue by rrobinet** [jameszah/ESP32-CAM-Video-Recorder#13]
Thanks for publishing this code.
That's what I am looking for, however adding an external sensor to trigger the camera is cumbersome, typically when trying to integrate all the hardware in an existing fake camera box.
Did you look at:
https://eloquentarduino.github.io/2020/01/motion-detection-with-esp32-cam-only-arduino-version/
This is what I am trying to implement concurrent to your code to trigger the SD data store. I will let you know if I succeed....;-)
I am also looking to add a real-time connection from the WEB interface, and automate the FTP transfer to a server running an avi viewer, may be triggered by a published MQTT message to a broker.
Adding basic security to access the Camera could be also nice .
So plenty of ideas, anyway thanks already for your development

Robert

**Comment by jameszah** [comment]
Have you seen this one over in the closed issues.   It has the software motion detection, rather than the external sensor.

That solution requires lots of batteries to keep the camera and CPU comparing pictures.

https://github.com/jameszah/ESP32-CAM-Video-Recorder/issues/6#issue-585719203
