### ISSUE TITLE
can not find "core-version.h" 

### ISSUE THREAD

**Issue by student1704** [jameszah/ESP32-CAM-Video-Recorder#18]
The ide complains "core-version.h" ... no such directory.
Which lib is missing?

**Comment by jameszah** [comment]
It must be something to do with your Arduino Board Library.

Go to Tools - Board - and make sure it is AI Thinker ESP32-CAM ... or ESP32 Wrover Module 

And go to Boards Manager to make sure they are installed and updated.

**Comment by student1704** [comment]
I switched to V89 and the problem does not occur.
