### ISSUE TITLE
PIR stay active

### ISSUE THREAD

**Issue by vr6syncro** [jameszah/ESP32-CAM-Video-Recorder#20]
PIR Touch is working fine.

But if i trigger a PIR signal with 3.3v and 1k resistor on Pin13 first there were no massage about triggered pir on console.
After i erase flash and reuploading it worked once but now pir stays triggered. and does not reset. 

I triggered PIR signal with a wire and 1k resistor and no pir sensor but i think it will be the same.

And second issues is i can connect to ftp but there are no files. if i look into the sd card there are files.

**Comment by jameszah** [comment]
You could add a debug statement to the loop() to see what the chip is seeing on the PIRpin.  And look at the web page to confirm pir is enabled.

`Serial.print( digitalRead(PIRpin) ); `

Or uncomment a debug statement at the beginning of PIR_ISR() to see if it is triggering.

ftp?  Make sure it is passive mode, port 21, esp/esp for name and password, and look in the correct directory that is based on the current date ... if you are not getting the date correctly in will be 1970. ???

**Comment by vr6syncro** [comment]
hey, thanks for reply

`ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1216
ho 0 tail 12 room 4
load:0x40078000,len:9720
ho 0 tail 12 room 4
load:0x40080400,len:6352
entry 0x400806b8
⸮

---
setup, core 1, priority = 1
                                    
-------------------------------------
ESP-CAM Video Recorder v89
 http://ESP32-CAM.local - to access the camera
-------------------------------------
Boot number: 1
Wakeup was not caused by deep sleep: 0
Get took 2
Good settings in the EPROM 
Internet_Enabled 1
DeepSleepPir 0
record_on_reboot 0
PIRpin 13
PIRenabled 1
framesize 10
repeat_config 300
xspeed 300
gray 0
quality 12
capture_interval 10000
total_frames_config 360
xlength 10
EnableBOT 1
Starting wifi ...
 Disable brownout

Brown regsiter was (in hex)40028000
.
Internet connected
mDNS responder started 'ESP32-CAM'
Local time: Sun Aug 23 17:08:14 2020

 Enable brownout
Starting sd card ...
SD card mount successfully!
Name: USD  
Type: SDHC/SDXC
Speed: 40 MHz
Size: 30207MB
SD_MMC Begin: 1
Starting server ...
http task prio: 5
Camera http started
Starting ftp ...
Total space: 1999MB
Used space: 20MB
Starting tasks ...
camera, core 1, priority = 2
aviwriter, core 1, priority = 3
ftp, core 0, priority = 4
Starting camera ...
PIRpin = 1, 1, 1, 1, 1,  
Touch T5 = 37, 37, 37, 37, 37,  
Camera Ready! Use 'http://192.168.2.244' to connect
Start a PIR
zthe loop, core 1, priority = 1
Taking a picture for file ...
zFile saved: /sdcard/20200823/ESP32-CAM 2020-08-23 17.08.18 uxga_Q12_I10000_L10_S300.jpg
Taking a picture for telegram...
Sending Photo Telegram, bytes: 384000
zz*****z*************z**************z************z***************z***************z***http index, core 0, priority = 5
*capture, core 0, priority = 5
**z***z**********zzzzzzzzz*************z****************z****************z***************z****************z****************z*******zzzzz
Photo telegram failed ><
z 
Starting an avi 

File name will be >/sdcard/20200823/ESP32-CAM 2020-08-23 17.08.50 uxga_Q12_I10000_L10_S300.avi<

Recording 1 video frames ...

PIR Interupt>> 3
PIR Interupt>> 3
PIR Interupt>> 3
PIR Interupt>> 0
PIR Interupt>> 0
PIR Interupt>> 0
PIR Interupt>> 3
PIR frames = 2
#Add another 10 seconds
PIR Interupt>> 3
PIR Interupt>> 0
PIR Interupt>> 0
PIR Interupt>> 0
PIR Interupt>> 0
PIR Interupt>> 0
PIR Interupt>> 0
PIR Interupt>> 1
PIR Interupt>> 3
PIR Interupt>> 0
PIR Interupt>> 0
PIR Interupt>> 0
PIR Interupt>> 0
PIR Interupt>> 0
PIR Interupt>> 3
PIR Interupt>> 3
`

PIR trigger just after reboot. the pir interupt start when touching the pin, hit the pin with the resistor or hit ground or 3.3v
In the webbroser pir is always 1.

If i connect ftp the console show: 226 3 matches total
Flashfxp log:
`[R] Connecting to espcam -> IP=192.168.2.244 PORT=21
[R] Connected to espcam
[R] 220--- Welcome to FTP for ESP8266 ---
[R] 220---   By David Paiva   ---
[R] 220 --   Version FTP-2016-01-14   --
[R] USER esp
[R] 331 OK. Password required
[R] PASS (hidden)
[R] 230 OK.
[R] SYST
[R] 500 Unknow command
[R] FEAT
[R] 500 Unknow command
[R] REST 100
[R] 500 Unknow command
[R] This site may not allow file resuming
[R] PWD
[R] 257 "/" is your current directory
`
no folders.

**Comment by jameszah** [comment]
The PIR seems to be switching off and on between 0 and 3 which looks good.

You have it set to record a frame every 10 seconds (10,000 ms), and the PIR runs for 15 seconds, and it is supposed to add another 10 seconds if the PIR is active in the last 5 seconds of the original 15 seconds.  So you might be getting movies with only 1 frame, which may not work -- my code my fail at the 1 frame movie.  Try switching it to interval of 100 ms or 500 ms, and then the movie will get running and you can modify the sensitivity of the pir if it is stopping when you want it to continue.  And you have there the message about adding another 10 seconds.  Is the problem that the movie never stops recording???

The ftp shows the "unknown command" which suggests that your ftp client is sending commands that this implementation of ftp does not handle.  I have tested it with FileZilla and WinSCP and CoffeeCup Free Ftp which all work, and rasparian command line ftp which works.  But Windows command line ftp does not, and Chrome Browser ftp does not work, so try FileZilla - I think is a popular, free, and multi-platform.

**Comment by jameszah** [comment]
Another PIR issue, is that you have the BOT turned on, which takes several seconds, and maybe many seconds if you have it set for UXGA, so the recording does not start until after that, when the motion has left.  Try shutting off the BOT, and test the PIR alone, before turning the BOT back on.  

I also see that you have a photo of 384000 bytes which I think is code for the camera didn't work correctly.  A UXGA is usually 100,000 to 150,000.  Try setting it to VGA while de-bugging, and switch back to UXGA and BOT when things are working.
