### ISSUE TITLE
Delete fork Task

### ISSUE THREAD

**Issue by liox1985** [jameszah/ESP32-CAM-Video-Recorder#30]
Hello Sir,

Is there any provision if SD card full with memory.. so ESP-CAM start check old video and deleting .. 
it will keep minimum current week/month data..as per configuration.

**Comment by jameszah** [comment]
I've thought about that off and on.  Maybe delete after 8 (?) days, or delete at 10% free space.
I have it on my list.

**Comment by jameszah** [comment]
https://github.com/jameszah/ESP32-CAM-Video-Recorder/tree/master/v98

Try this.  It deletes the oldest day of videos whenever you SD hits 90% full.
