### ISSUE TITLE
Is it possible to include the field input for a user telegram token,wifi name&password? on a control web page interface,for flexibility to users? 

### ISSUE THREAD

**Issue by dollatron** [jameszah/ESP32-CAM-Video-Recorder#33]

**Comment by jameszah** [comment]
I've got WiFiManager configuration on my todo list.
Originally I was going to set up camera with it, but I did that with the /start calls, but still needs the ssid and telegram config ...
Working on a few other things first. 😄

**Comment by dollatron** [comment]
> 
> 
> I've got WiFiManager configuration on my todo list.
> Originally I was going to set up camera with it, but I did that with the /start calls, but still needs the ssid and telegram config ...
> Working on a few other things first. 😄

ok that will be superb, i have been trying to make it so .

**Comment by toome123** [comment]
Here is some library that looks nice and I think will do the job.. [https://github.com/Hieromon/AutoConnect](https://github.com/Hieromon/AutoConnect)

**Comment by dollatron** [comment]
> 
> 
> Here is some library that looks nice and I think will do the job.. https://github.com/Hieromon/AutoConnect

thanks mate
