### ISSUE TITLE
TimeZone not changing

### ISSUE THREAD

**Issue by saxie** [jameszah/ESP32-CAM-Video-Recorder#34]
When setting timezone to:  #define TIMEZONE "GMT+2" the time is set for the wrong timezone. 

what would the correct TZ string be for South Africa ? GMT+2, no DST

**Comment by saxie** [comment]
I solved it - all my fault. Timezone should be "GMT-2" for South Africa

**Comment by jameszah** [comment]
First guess -- Helsinki, Finland 
EET-2EEST-3,M3.5.0/03:00:00,M10.5.0/04:00:00

or after removing the dst:

EET-2

**Comment by saxie** [comment]
Thanks for the reply!

 

I did finally manage to get it working. GMT-2 J

 

EET-2 would have worked to I’m sure

 

Great Project!

 

W
