### ISSUE TITLE
I can't download anything from ftp server

### ISSUE THREAD

**Issue by bogdanys** [jameszah/ESP32-CAM-Video-Recorder#37]
Hi! I tried to record something, but when I want to download the record from ftp, I can't. The response is "This site can't be reached. Might be temporarily down or it may have moved permanently to a new web adress. To acces the ftp server I use Chrome. It is necesary to use a dedicated app like FileZila? Thank you for your answer.

**Comment by jameszah** [comment]
You cannot Chrome for downloads.  It works to list files, but then it used a strange feature of ftp to download, and Chrome has deprecated ftp entirely now, so I did not implement that strange feature into the esp32 ftp I was using.

Plus the Filezilla, etc give you nice features like deleting and bulk downloads, etc.
