### ISSUE TITLE
How can I add the / photo and / flash function in telegram in the v98 version

### ISSUE THREAD

**Issue by Kevinsbkx** [jameszah/ESP32-CAM-Video-Recorder#39]
You are doing an amazing job helping improve home security. Thank you.

**Comment by jameszah** [comment]
You want to send /photo and /flash from a web browser??  

The camera is recording continuously, so you don't really need an individual photo - you already have thousands in the avi.

You could look here https://github.com/jameszah/ESP32-Cam-Telegram for sending photos to telegram, or the random nerd has some sample programs to take a single photo.  https://randomnerdtutorials.com/esp32-cam-take-photo-display-web-server/

Also if you are using the SD card, the bright LED (aka The Blinding Disk Active Light) is connected to the SD card, and can interfere with some SD cards.
