### ISSUE TITLE
question for the offline recorder(using only sd card)

### ISSUE THREAD

**Issue by nices0325** [jameszah/ESP32-CAM-Video-Recorder#41]
hello there.. 

nowadays, I'm planning to make a offline recorder (using only sd card) for my own project..

Since the codes you wrote are hard for me to understand that I'm not a major programmer..

Can you get me some tips for removing wifi codes and using esp32 camera logging (log to sdcard) ?

Thanks for your awesome library!

**Comment by al3xv0lk** [comment]
Just use the Junior version from here: https://github.com/jameszah/ESP32-CAM-Video-Recorder-junior
And then add this to auto delete old files: https://github.com/jameszah/ESP32-CAM-Video-Recorder-junior/issues/6

**Comment by nices0325** [comment]
Thanks for replying!!
I do appreciate
