### ISSUE TITLE
Library time.h

### ISSUE THREAD

**Issue by JFJO** [jameszah/ESP32-CAM-Video-Recorder#45]
Bonjour 
j'ai apprécié votre code
Mais je n'arrive pas à obtenir la date pour l'enregistrement des photos et des videos.
Je pense que cela vient du fichier time.h
J'ai mis à jour avec Time-1.6.0.zip 
https://github.com/PaulStoffregen/Time
![ecran_serveur](https://user-images.githubusercontent.com/30812918/110663899-330e9200-81c7-11eb-99f6-1b8c3e782225.jpg)
Ce fichier est remplacé par Timelib.h
Quand j'utilise Timelib.h j'ai de nombreuses erreur de compilation.

Merci de me conseiller pour solutionner mon problème.

**Comment by jameszah** [comment]
**But I can't seem to get the date for recording the photos and videos.**

Do you have internet access from the esp32?   Are there firewalls blocking the esp32 from calling for time, and time getting back to the esp32.

This code fetches the date from pool.ntp.org -- you might try an alternate time server for your area.  Find some here https://www.ntppool.org/en/

```
configTime(0, 0, "pool.ntp.org");

  setenv("TZ", TIMEZONE, 1);  // mountain time zone from #define at top
  tzset();
```

Then this code loops until it gets a date returned, before giving up after too many retry_count.

```
  while (timeinfo.tm_year < (2016 - 1900) && ++retry < retry_count) {
    Serial.printf("Waiting for system time to be set... (%d/%d) -- %d\n", retry, retry_count, timeinfo.tm_year);
    delay(1000);
    time(&now);
    localtime_r(&now, &timeinfo);
  }
```

You don't need any more time libraries or includes.
