### ISSUE TITLE
ESP32 Wrover Module error?

### ISSUE THREAD

**Issue by degagevip** [jameszah/ESP32-CAM-Video-Recorder#49]
The is Arduino code, with standard setup for ESP32-CAM
    - Board ESP32 Wrover Module
    - Partition Scheme Huge APP (3MB No OTA)

arduino 1.8.13
espressif systems 1.04
v98x-WiFiMan

Error compiling for development board esp32 wrover module

Why not?

**Comment by jameszah** [comment]
Maybe you could paste the errors for me to have a look.

**Comment by degagevip** [comment]
Thanks to jameszah , 
because I have modified the WiFimanager.h code before! Did not read the printed information carefully.
The bug is fixed. The program is great

**Comment by ashish-iottive** [comment]
> Thanks to jameszah ,
> because I have modified the WiFimanager.h code before! Did not read the printed information carefully.
> The bug is fixed. The program is great

Hey @degagevip if you have successfully executed Camera Webserver with WiFi Manager then could you share the Arduino sketch for that only which include the Basic Example Webserver with Wifi Manager.It would be great help.

**Comment by degagevip** [comment]
hi,ashish-iottive
In terms of software, I didn't make much improvement. I just added solar charging chip, fill light and 18650 battery to the circuit. I will arrange the PCB and announce it in the near future.

**Comment by ashish-iottive** [comment]
Hey @degagevip I have figured out the WiFi Manager library in the ESP32-Camera Webserver sketch, in this sketch I have set an static IP which can be viewed in WiFi Manager portal to remove the use of Serial Monitor and a button to reset the Wi-Fi Manager settings and added mDNS to advertising the IP Address of the camera.
