### ISSUE TITLE
C++ compile errors

### ISSUE THREAD

**Issue by boomyville** [jameszah/ESP32-CAM-Video-Recorder#52]
I'm getting a whole bunch of errors when compiling the .cpp files in arduino
I had no issues with an older installation of Arduino but with the new one I'm getting errors such as:

TimeLapseAvi94x:776:77: error: format '%d' expects argument of type 'int', but argument 8 has type 'long int' [-Werror=format=]
     sprintf(the_page, msg, vernum, devname, localip, use, tot, rssi, strdate);  //fname

TimeLapseAvi94x:835:75: error: format '%d' expects argument of type 'int', but argument 8 has type 'long int' [-Werror=format=]
   sprintf(the_page, msg, vernum, devname, localip, use, tot, rssi, strdate);  //fname

Anyone have any idea in addressing this? I'm sure its just an option in Arduino that can fix this as I had no issues compiling and uploading the code previously

**Comment by jameszah** [comment]
Check this:

![image](https://user-images.githubusercontent.com/36938190/117920686-8d51cf00-b2ac-11eb-8d35-f4ee5eaee3f0.png)
