### ISSUE TITLE
Thanks for your sharing.

### ISSUE THREAD

**Issue by fustyles** [jameszah/ESP32-CAM-Video-Recorder#53]
I had modified your code. I fondly anticipate your reply. Thank you very much.
https://github.com/fustyles/Arduino/blob/master/ESP32-CAM-Video-Recorder-junior-Page/ESP32-CAM-Video-Recorder-junior-Page.ino

https://www.youtube.com/watch?v=k7DqiOUUE2A

I found the bug below.
cname.toCharArray(devname, cname.length());
modify  to
cname.toCharArray(devname, cname.length() + 1);

**Comment by jameszah** [comment]
Thanks -- which file is that problem?  It seems to have been corrected here, but not in other/older versions.

https://github.com/jameszah/ESP32-CAM-Video-Recorder-junior/blob/e10ab295d0f1bc21420b5162787cbd528820498b/ESP32-CAM-Video-Recorder-junior-50x-lpmod.ino#L589
