### ISSUE TITLE
Black avi problem

### ISSUE THREAD

**Issue by mehceunisen** [jameszah/ESP32-CAM-Video-Recorder#55]
Hello, first of all I implemented the code to esp-idf, it starts the avi, adds frame buffers to avi correctly however when i try to play video, on vlc its not playing but on windows media player classic its plays as fully black video. Any ideas??

**Comment by jameszah** [comment]
Well, the lens-cap is always a possibility.  😄 

I think it is a camera problem.
The camera might be bad, or not connected nicely to the module -- so you could try another camera, or just pull it off and re-connect it.

You could also look at the stats for average frame size that are printed at the bottom of the serial monitor after the video.  You might be getting an "empty buffer" of 32kb or something depending how you have framesize and quality.

Actually the esp-idf could bring in all sorts of interesting issues.  How about try the other version ... 
 https://github.com/jameszah/ESP32-CAM-Video-Recorder-junior
which uses all the latest arduino-esp32 libraries (latest non-experimental).  I think esp-idf would have even more modern esp32 libraries which might cause some problems.  Is there a little printout at the bottom of the esp-idf compile and link that states exactly which libraries are involved.   

I have only experimented briefly with esp-idf, and platform-io just a little more.

Are there major adjustments for esp-idf?
