### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by navdeepssidhu** [jameszah/ESP32-CAM-Video-Recorder#69]
Hi, 
I am using Arduino 1.8.19 and ESP32 2.0.2 in board manager and Wroover  with Huge app setting. I am not able to run A1 ans V99. While compiling I am getting Error : compiling for board ESP32 Wrover Module. Though V98 is compiling without any issue. Any help is appreciable.  My camera module is AI-Thinker. Thanks 
Nav

**Comment by jameszah** [comment]
Could you paste the list of errors, with detailed error reporting turned on from Adruino - Preferences.

Double check you have 2.02 and have restarted the Arduino ide after installing it.  Those latest versions were created when 2.0x came out and it wouldn't compile.

**Comment by navdeepssidhu** [comment]
Hi, sorry for the trouble. I found that updating WiFi library resolved the issue. 
Thanks
