### ISSUE TITLE
Modify xspeed parameter for long timelapse

### ISSUE THREAD

**Issue by jameszah** [jameszah/ESP32-CAM-Video-Recorder#8]
The xspeed parameter is the multiple of fps to playback the video.

If you are taking pictures at 10,000 ms interval (0.1 fps), and you want them to play at 24 fps (or 41.7 ms interval), then xspeed would be 24 / .1 = 240   or 10,000 / 41.7.

So I think you need to speed up your 2 frames per hour to a xspeed factor of 43,200 ... I think.

I haven't tried that -- I get a little nervous in power supplies and people knocking over the camera to stretch beyond 1 hour, before closing the files, writing the index, and starting a new video.  My tomato videos run for 1 hour at 50x speed, and then I paste the daylight hours together and multiply it by another 32 times for 1600x.  One day in 30 seconds.  But grass is a whole new world of slowness!  :-)

@bencooney

**Comment by bencooney** [comment]
Thanks, for that advice @jameszah - I'm still exploring options for long intervals between captured frames. I got the impression that int limits might be causing issues. But don't have any evidence for that. 

I'm pointing mine at some Xanthorrhoea/Australian Grass Tree seedlings which are ridiculously slow growing. The position and power are fairly reliable but tests are slow to execute.
